### ISSUE TITLE
 Where to download the data used in the code 

### ISSUE THREAD

**Issue by poctrrt** [bydata/30DayChartChallenge#1]
There is only code inside, I want to ask where the data of the sample code can be downloaded, can you pass the data?

**Comment by bydata** [comment]
Hi @poctrrt, apologies for having missed your question for half a year. Typically, I don't own the data so that I can share it. I use open data for many charts and usually document where I downloaded the data in case I didn't access it directly from the script.

Are you looking for a specific data source? Maybe I can help.

Cheers,
Ansgar
